<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class rekomendasi_admin_kependudukan extends Model
{
    public $table = 'rekomendasi_admin_kependudukans';

    public $fillable = [
        // 'file_ktp_terlapor_minkep',
        'no_pendaftaran_minkep',
        'id_provinsi_minkep',
        'id_kabkot_minkep',
        'id_kecamatan_minkep',
        'id_kelurahan_minkep',
        'jenis_pelapor_minkep',
        'ada_nik_minkep',
        'nik_minkep',
        'no_kk_minkep',
        'nama_minkep',
        'tempat_lahir_minkep',
        'tgl_lahir_minkep',
        'jenis_kelamin_minkep',
        'telp_minkep',
        'email_minkep',
        'alamat_minkep',
        'status_dtks_minkep',
        'file_ktp_terlapor_minkep',
        'file_kk_terlapor_minkep',
        'file_keterangan_dtks_minkep',
        'file_pendukung_minkep',
        'catatan_minkep',
        'tujuan_minkep',
        'status_aksi_minkep',
        'petugas_minkep',
        'Nomor_Surat',
        'validasi_surat',
        'createdby_minkep',
        'updatedby_minkep',
        'created_at',
        'updated_at',
    ];
    protected $casts = [
        'no_pendaftaran_minkep'=> 'string',
        'id_provinsi_minkep'=> 'string',
        'id_kabkot_minkep'=> 'string',
        'id_kecamatan_minkep'=> 'string',
        'id_kelurahan_minkep'=> 'string',
        'jenis_pelapor_minkep'=> 'string',
        'ada_nik_minkep'=> 'string',
        'nik_minkep'=> 'string',
        'no_kk_minkep'=> 'string',
        'nama_minkep'=> 'string',
        'tempat_lahir_minkep'=> 'string',
        'tgl_lahir_minkep'=> 'string',
        'jenis_kelamin_minkep'=> 'string',
        'telp_minkep'=> 'string',
        'email_minkep'=>'string',
        'alamat_minkep'=> 'string',
        'status_dtks_minkep'=> 'string',
        'file_ktp_terlapor_minkep'=> 'string',
        'file_kk_terlapor_minkep'=> 'string',
        'file_keterangan_dtks_minkep'=> 'string',
        'file_pendukung_minkep'=> 'string',
        'catatam_minkep'=> 'string',
        'tujuan_minkep'=> 'string',
        'status_aksi_minkep'=> 'string',
        'petugas_minkep'=> 'string',
        'createdby_minkep'=> 'string',
        'updatedby_minkep'=> 'string',
        'created_at'=> 'string',
        'updated_at'=> 'string'
    ];

    public static array $rules = [
        'no_pendaftaran_minkep'=>'required',
        'id_provinsi_minkep'=>'required',
        'id_kabkot_minkep'=>'required',
        'id_kecamatan_minkep'=>'required',
        'id_kelurahan_minkep'=>'required',
        'jenis_pelapor_minkep'=>'required',
        'ada_nik_minkep'=>'required',
        'nik_minkep'=>'required',
        'no_kk_minkep'=>'required',
        'nama_minkep'=>'required',
        'tempat_lahir_minkep'=>'required',
        'tgl_lahir_minkep'=>'required',
        'jenis_kelamin_minkep'=>'required',
        'telp_minkep'=>'required',
        'email_minkep'=>'required',
        'alamat_minkep'=>'required',
        'status_dtks_minkep'=>'required',
        'file_ktp_terlapor_minkep'=>'required',
        'file_kk_terlapor_minkep'=>'required',
        'file_keterangan_dtks_minkep'=>'required',
        'file_pendukung_minkep'=>'required',
        'catatam_minkep'=>'required',
        'tujuan_minkep'=>'required',
        'status_aksi_minkep'=>'required',
        'petugas_minkep'=>'required',
        'createdby_minkep'=>'required',
        'updatedby_minkep'=>'required',
        'created_at'=>'required',
        'updated_at'=>'required'
    ];
}
